### ISSUE TITLE
Misidentification of docx files

### ISSUE THREAD

**Issue by katyo** [aahancoc/tree_magic#11]
It seems **.docx** is missing in mime database.
I don't sure this is problem of *treemagic* itself.

```
doc.doc:
    magic: application/msword
    treemagic: application/msword
doc.odt:
    magic: application/vnd.oasis.opendocument.text
    treemagic: application/vnd.oasis.opendocument.text
doc.docx:
    magic: application/vnd.openxmlformats-officedocument.wordprocessingml.document
    treemagic: application/zip
```
